spring:
  cloud:
    gateway:
      routes: #配置路由路径
        - id: cms-main-route
          uri: lb://cms-main-service
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: cms-auth-route
          uri: lb://cms-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8081/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: ${env.addr}
    password: redis12530798

secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"